# Generated by Django 5.0.7 on 2024-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='option_picture',
            field=models.ImageField(blank=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_picture',
            field=models.ImageField(blank=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
