# Generated by Django 5.0.7 on 2024-08-05 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_option_option_remove_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
